language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

before_install:
  - docker-compose --version
  - docker --version

script:
  - docker-compose up --build
